"use client";

import { useState } from "react";
import Link from "next/link";
import { AlertCircle, CreditCard, Lock, ShoppingBag } from "lucide-react";
import { Elements, PaymentElement, useElements, useStripe } from "@stripe/react-stripe-js";
import { loadStripe } from "@stripe/stripe-js";
import { BrandButton } from "@/components/primitives";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { formatUSD } from "@/lib/format";
import { preparePayment } from "@/lib/cart/actions";
import { useCart, getCartSubtotal, getCartCount } from "@/lib/cart/store";
import { appendOrder } from "@/lib/orders/store";
import { shippingFeeCents } from "@/lib/payments/shipping";

const key=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY??"";
const stripePromise=key?loadStripe(key):null;
const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const COUNTRIES=[["US","United States"],["CA","Canada"],["GB","United Kingdom"],["AU","Australia"],["DE","Germany"],["FR","France"],["IN","India"],["JP","Japan"],["CN","China"],["SG","Singapore"],["CH","Switzerland"],["NL","Netherlands"],["BE","Belgium"],["IT","Italy"],["ES","Spain"],["AE","United Arab Emirates"]] as const;
interface Address{firstName:string;lastName:string;company:string;address1:string;city:string;state:string;postal:string;country:string}
interface FormState{email:string;phone:string;shipping:Address;billing:Address}
const emptyAddress=():Address=>({firstName:"",lastName:"",company:"",address1:"",city:"",state:"",postal:"",country:"US"});

export function CheckoutView(){
  const items=useCart(),subtotal=getCartSubtotal(items),count=getCartCount(items);
  const [form,setForm]=useState<FormState>({email:"",phone:"",shipping:emptyAddress(),billing:emptyAddress()});
  const [billingSame,setBillingSame]=useState(true),[errors,setErrors]=useState<Record<string,string>>({});
  const [preparing,setPreparing]=useState(false),[submitError,setSubmitError]=useState<string|null>(null);
  const [payment,setPayment]=useState<{clientSecret:string;orderId:string;orderNumber:string;total:number}|null>(null);
  const requiresDryIce=items.some(i=>i.requiresDryIce);
  const shipping=shippingFeeCents(form.shipping.country,requiresDryIce)/100,total=subtotal+shipping;
  function address(kind:"shipping"|"billing",field:keyof Address,value:string){setForm(f=>({...f,[kind]:{...f[kind],[field]:value}}));setErrors(e=>({...e,[`${kind}.${field}`]:""}));}
  function validate(){const next:Record<string,string>={};if(!emailRegex.test(form.email))next.email="Valid email required.";const sets:Array<[string,Address]>=[["shipping",form.shipping]];if(!billingSame)sets.push(["billing",form.billing]);for(const[prefix,a]of sets)for(const field of["firstName","lastName","company","address1","city","state","postal"]as const)if(!a[field].trim())next[`${prefix}.${field}`]="Required.";setErrors(next);return!Object.keys(next).length;}
  async function continueToPayment(event:React.FormEvent){event.preventDefault();if(!validate())return;setPreparing(true);setSubmitError(null);const s=form.shipping,b=billingSame?s:form.billing;const result=await preparePayment({customer:{name:`${s.firstName} ${s.lastName}`.trim(),email:form.email,phone:form.phone,company:s.company,address1:s.address1,postal_code:s.postal,country:s.country,shippingAddress:s,billingAddress:b},items:items.map(i=>({productId:i.productId,variantId:i.variantId,quantity:i.quantity}))});if(!result.ok){setSubmitError(result.error);setPreparing(false);return;}appendOrder({orderId:result.orderNumber,internalOrderId:result.orderId,placedAt:new Date().toISOString(),customerEmail:form.email,customerName:`${s.firstName} ${s.lastName}`.trim(),subtotal:result.total,lines:items.map(i=>({productId:i.productId,variantId:i.variantId,name:i.name,variantName:i.variantName,quantity:i.quantity,unitPrice:i.unitPrice,image:i.image,href:i.href}))});setPayment({clientSecret:result.clientSecret,orderId:result.orderId,orderNumber:result.orderNumber,total:result.total});setPreparing(false);}
  if(!count)return <Empty/>;
  if(payment){const billing=billingSame?form.shipping:form.billing;return <Elements stripe={stripePromise} options={{clientSecret:payment.clientSecret,appearance:{theme:"stripe"}}}><PaymentStep amount={payment.total} billing={billing} email={form.email} orderId={payment.orderId} orderNumber={payment.orderNumber} onBack={()=>setPayment(null)}/></Elements>;}
  return <form noValidate onSubmit={continueToPayment} className="grid gap-8 lg:grid-cols-[1.4fr_1fr] lg:gap-12"><div className="space-y-8"><fieldset className="space-y-4"><legend className="type-h3">Contact</legend><Field id="co-email" label="Email *" error={errors.email}><Input id="co-email" type="email" autoComplete="email" value={form.email} onChange={e=>setForm(f=>({...f,email:e.target.value}))}/></Field><Field id="co-phone" label="Phone"><Input id="co-phone" type="tel" autoComplete="tel" value={form.phone} onChange={e=>setForm(f=>({...f,phone:e.target.value}))}/></Field></fieldset><AddressFields title="Shipping address" prefix="shipping" value={form.shipping} errors={errors} onChange={(f,v)=>address("shipping",f,v)}/><fieldset className="space-y-4"><legend className="type-h3">Billing address</legend><label className="flex items-center gap-3 rounded-[var(--radius-md)] border bg-white p-4 text-sm font-medium"><input type="checkbox" checked={billingSame} onChange={e=>setBillingSame(e.target.checked)}/>Billing address is the same as shipping</label>{!billingSame?<AddressFields prefix="billing" value={form.billing} errors={errors} onChange={(f,v)=>address("billing",f,v)}/>:null}</fieldset></div><Summary items={items} subtotal={subtotal} shipping={shipping} total={total} requiresDryIce={requiresDryIce}><BrandButton type="submit" size="lg" disabled={preparing||!stripePromise} className="mt-6 w-full"><CreditCard className="size-4"/>{preparing?"Preparing payment…":"Continue to payment"}</BrandButton>{!stripePromise?<Error message="Stripe payment is not configured."/>:null}{submitError?<Error message={submitError}/>:null}</Summary></form>;
}

function PaymentStep({amount,billing,email,orderId,orderNumber,onBack}:{amount:number;billing:Address;email:string;orderId:string;orderNumber:string;onBack:()=>void}){const stripe=useStripe(),elements=useElements();const[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);async function submit(e:React.FormEvent){e.preventDefault();if(!stripe||!elements)return;setBusy(true);setError(null);const result=await stripe.confirmPayment({elements,confirmParams:{return_url:`${window.location.origin}/checkout/success?order_id=${encodeURIComponent(orderId)}&order_number=${encodeURIComponent(orderNumber)}`,payment_method_data:{billing_details:{name:`${billing.firstName} ${billing.lastName}`.trim(),email,address:{line1:billing.address1,city:billing.city,state:billing.state,postal_code:billing.postal,country:billing.country}}}}});if(result.error){setError(result.error.message??"Payment could not be completed.");setBusy(false);}}return <form onSubmit={submit} className="mx-auto grid max-w-3xl gap-8 lg:grid-cols-[1.3fr_.7fr]"><section className="rounded-[var(--radius-xl)] border bg-white p-6 lg:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="type-overline text-[var(--color-muted)]">Secure checkout</p><h2 className="type-h3">Payment information</h2></div><Lock className="size-5 text-[var(--color-brand)]"/></div><PaymentElement options={{layout:"tabs"}}/>{error?<Error message={error}/>:null}</section><aside className="rounded-[var(--radius-xl)] border bg-white p-6 lg:self-start"><p className="text-sm text-[var(--color-muted-foreground)]">Order #{orderNumber}</p><div className="mt-4 flex justify-between border-y py-4"><b>Total</b><b className="text-xl">{formatUSD(amount)}</b></div><BrandButton type="submit" size="lg" disabled={!stripe||!elements||busy} className="mt-6 w-full"><Lock className="size-4"/>{busy?"Processing…":"Place order"}</BrandButton><button type="button" onClick={onBack} disabled={busy} className="mt-4 w-full text-sm font-medium text-[var(--color-brand)] underline">Back to addresses</button><p className="mt-4 text-center text-xs text-[var(--color-muted)]">Encrypted and securely processed by Stripe.</p></aside></form>}
function AddressFields({title,prefix,value,errors,onChange}:{title?:string;prefix:"shipping"|"billing";value:Address;errors:Record<string,string>;onChange:(f:keyof Address,v:string)=>void}){const input=(field:keyof Address,label:string,auto:string)=><Field id={`${prefix}-${field}`} label={label} error={errors[`${prefix}.${field}`]}><Input id={`${prefix}-${field}`} autoComplete={`${prefix} ${auto}`} value={value[field]} onChange={e=>onChange(field,e.target.value)}/></Field>;const body=<><div className="grid gap-4 sm:grid-cols-2">{input("firstName","First name *","given-name")}{input("lastName","Last name *","family-name")}</div>{input("company","Organization *","organization")}{input("address1","Address *","address-line1")}<div className="grid gap-4 sm:grid-cols-2">{input("city","City *","address-level2")}{input("state","State / Region *","address-level1")}</div><div className="grid gap-4 sm:grid-cols-2">{input("postal","Postal code *","postal-code")}<Field id={`${prefix}-country`} label="Country"><select id={`${prefix}-country`} value={value.country} onChange={e=>onChange("country",e.target.value)} className="h-10 w-full rounded-[var(--radius-md)] border bg-white px-3 text-sm">{COUNTRIES.map(([c,l])=><option key={c} value={c}>{l}</option>)}</select></Field></div></>;return title?<fieldset className="space-y-4"><legend className="type-h3">{title}</legend>{body}</fieldset>:<div className="space-y-4">{body}</div>}
function Summary({items,subtotal,shipping,total,requiresDryIce,children}:{items:ReturnType<typeof useCart>;subtotal:number;shipping:number;total:number;requiresDryIce:boolean;children:React.ReactNode}){return <aside className="lg:sticky lg:top-28 lg:self-start"><div className="rounded-[var(--radius-xl)] border bg-white p-6"><h2 className="type-h3">Order summary</h2><ul className="mt-5 space-y-3">{items.map(i=><li key={`${i.productId}:${i.variantId??""}`} className="flex justify-between gap-3 text-sm"><span><b>{i.quantity}×</b> {i.name}{i.variantName?` · ${i.variantName}`:""}</span><b>{formatUSD((i.unitPrice??0)*i.quantity)}</b></li>)}</ul><div className="mt-5 space-y-2 border-t pt-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{formatUSD(subtotal)}</b></div><div className="flex justify-between"><span>Shipping{requiresDryIce?" (dry ice)":""}</span><b>{formatUSD(shipping)}</b></div><div className="flex justify-between border-t pt-3 text-lg"><b>Total</b><b>{formatUSD(total)}</b></div></div><p className="mt-2 text-xs text-[var(--color-muted)]">Shipping updates from the selected country.</p>{children}<p className="mt-3 text-center text-xs text-[var(--color-muted)]">By continuing you agree to our <Link href="/legal/terms" className="underline">terms</Link>.</p></div></aside>}
function Empty(){return <div className="mx-auto flex max-w-xl flex-col items-center gap-6 rounded-[var(--radius-xl)] border border-dashed bg-white p-12 text-center"><ShoppingBag className="size-8"/><div><h2 className="type-h3">Nothing to check out</h2><p>Your cart is empty.</p></div><BrandButton href="/products">Browse products</BrandButton></div>}
function Error({message}:{message:string}){return <p role="alert" className="mt-3 flex gap-2 rounded-[var(--radius-md)] bg-[var(--color-danger)]/10 p-3 text-sm text-[var(--color-danger)]"><AlertCircle className="size-4 shrink-0"/>{message}</p>}
function Field({id,label,error,children}:{id:string;label:string;error?:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label htmlFor={id}>{label}</Label>{children}{error?<p role="alert" className="text-sm text-[var(--color-danger)]">{error}</p>:null}</div>}
